### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement google-crc32c==1.1.2 

### ISSUE THREAD

**Issue by punndcoder28** [googleapis/python-crc32c#69]
Getting an error while trying to install `google-crc32c` package on my M1 MacBook Air

#### Environment details

  - Programming language: Python
  - OS: Mac OS 11.4 (M1 Chip)
  - Language runtime version: Python 3.8.10
  - Package version: 1.1.2

#### Steps to reproduce

My project's requirements.txt file contains the packages list

  1. virtualenv venv-name
  2. source vent-name/bin/activate
  3. python -m pip install -r requirements-prod.txt

#### Error
```
Collecting google-crc32c==1.1.2
  Using cached google-crc32c-1.1.2.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/puneethk/Desktop/work/Backend/gt-push-service/venv-gt-push-service/bin/python3 /Users/puneethk/Desktop/work/Backend/gt-push-service/venv-gt-push-service/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/tmpfez2j9le
         cwd: /private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-install-came3isd/google-crc32c_ed52a642ee6945b0ab7a361f779837f2
    Complete output (42 lines):
    Traceback (most recent call last):
      File "/Users/puneethk/Desktop/work/Backend/gt-push-service/venv-gt-push-service/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
        main()
      File "/Users/puneethk/Desktop/work/Backend/gt-push-service/venv-gt-push-service/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/puneethk/Desktop/work/Backend/gt-push-service/venv-gt-push-service/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 68, in <module>
        main()
      File "setup.py", line 54, in main
        setuptools.setup(
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/puneethk/.pyenv/versions/3.8.10/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 455, in __init__
        _Distribution.__init__(self, {
      File "/Users/puneethk/.pyenv/versions/3.8.10/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 807, in finalize_options
        ep(self)
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/normal/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/normal/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/normal/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/google_crc32c_build.py", line 47, in <module>
        FFIBUILDER = cffi.FFI()
      File "/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/normal/lib/python3.8/site-packages/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/normal/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 2): no suitable image found.  Did find:
    	/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/normal/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so: mach-o, but wrong architecture
    	/private/var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/pip-build-env-d8uoxep9/normal/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so: mach-o, but wrong architecture
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a9/2c/2a055430b83aa62e74028423e562e0df70cd1146535057587a1167f6fa81/google-crc32c-1.1.2.tar.gz#sha256=dff5bd1236737f66950999d25de7a78144548ebac7788d30ada8c1b6ead60b27 (from https://pypi.org/simple/google-crc32c/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/puneethk/Desktop/work/Backend/gt-push-service/venv-gt-push-service/bin/python3 /Users/puneethk/Desktop/work/Backend/gt-push-service/venv-gt-push-service/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/g4/tg_7l93n41949f2j940zj9pr0000gn/T/tmpfez2j9le Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement google-crc32c==1.1.2 (from versions: 0.0.1, 0.0.2, 0.1.0, 1.0.0, 1.1.0, 1.1.1, 1.1.2)
ERROR: No matching distribution found for google-crc32c==1.1.2
```

**Comment by tseaver** [comment]
Your Python build does not have a suitable `cff1` available.  Can you show the output of `pip list` and `pip install --upgrade cffi`?

**Comment by punndcoder28** [comment]
Will check that thanks!

**Comment by crvv** [comment]
I got the same error.

```
$ pip list | grep cffi
cffi                        1.14.6
```

```
$ pip install --upgrade cffi
Requirement already satisfied: cffi in $HOME/.pyenv/versions/3.9.2/lib/python3.9/site-packages (1.14.6)
Requirement already satisfied: pycparser in $HOME/.pyenv/versions/3.9.2/lib/python3.9/site-packages (from cffi) (2.20)
```

**Comment by crvv** [comment]
workaround:

```
pip install cffi==1.14.1
cd python-crc32c
python setup.py install
```

The latest cffi is not supported on ARM Mac.
https://foss.heptapod.net/pypy/cffi/-/issues/464

**Comment by tseaver** [comment]
PR #106 switched our release machinery to use CIBuildWheel, which enabled building universal2 wheels. That PR should land in a release on Monday.

@punndcoder28, @crvv in the meanwhile, if you'd like to try out the `universal2` wheels, you can download the [artifact tarball](https://github.com/googleapis/python-crc32c/suites/3800123153/artifacts/93831382) from the test of that PR.
